spring:
  application:
    name: "store-service"
  cloud:
    kubernetes:
      config:
        namespace: bistroad-prod
swagger:
  doc:
    operation:
      store:
        get-store:
          description: Get a store by ID
        get-stores:
          description: Search stores
        get-nearby-stores:
          description: Search nearby stores within a specific radius
        post-store:
          description: Create a store
        put-store:
          description: Update or create a store
        patch-store:
          description: Update a store partially
        delete-store:
          description: Delete a store
        post-store-photo:
          description: Upload a store photo
      store-item:
        get-store-item:
          description: Get an item by ID
        get-store-items:
          description: Search items
        post-store-item:
          description: Create an item
        put-store-item:
          description: Update or create an item
        patch-store-item:
          description: Update an item partially
        delete-store-item:
          description: Delete an item
        post-store-item-photo:
          description: Upload a store item photo
    model:
      page:
        page:
          description: Page number
        size:
          description: Number of elements on a page
        sort:
          description: Sorting properties (e.g. sort=name,desc, sort=price,asc)